### ISSUE TITLE
weird to use basic** to set command properties

### ISSUE THREAD

**Issue by demarey** [pharo-spec/Commander2#10]
In a command, you need to use #basicName: and #basicDescription: to set the _static_ (as opposed to dynamic) properties of a command.
It looks strange that users have to often use a method looking as a low level method (starts with basic). I would rather use #name: and #description: and find a new name for the dynamic part.

**Comment by juliendelplanque** [comment]
I will address this when there will be a major release because this is a breaking change.

**Comment by juliendelplanque** [comment]
This is fixed in v2.0.0
