### ISSUE TITLE
shortcutKey: what is the type of the argument?

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Commander2#22]
I see 

shortcutKey: aString
 	shortcutKey := aString 

and users use 

asSpecCommand
	"Here we define the additional information the command will need to know
	 when used in the Spec framework.
	"
	^ super asSpecCommand
		shortcutKey: $n meta;
		yourself

**Comment by juliendelplanque** [comment]
The type depends on the UI framework used. But `aString` is definitely a bad name.

**Comment by juliendelplanque** [comment]
I fixed it in 15fdfb1
