### ISSUE TITLE
SpCommand>>iconNamed:

### ISSUE THREAD

**Issue by Ducasse** [pharo-spec/Commander2#23]
should be categorised as internal. 
As a user I should use

icon
iconName:
and 
iconProvider

Is it correct?

I would remove iconName:from: because I do not see the advantage of 
iconProvider:
iconName:

**Comment by juliendelplanque** [comment]
> should be categorised as internal.
> As a user I should use
> 
> icon
> iconName:
> and
> iconProvider
> 
> Is it correct?

Yes, I will categorise it as "private".
It is in "accessing" because in `Objec`t, this method is in "accessing" protocol.

> 
> I would remove iconName:from: because I do not see the advantage of
> iconProvider:
> iconName:

This is syntax sugar, just makes life of people easier.
But it indeed requires a comment to explain that.

**Comment by juliendelplanque** [comment]
Fixed in d97e834743c6077968a79e13b8221a5a46d9b257 and 1f8dd15b8e35ad19953c01f877da8259c921554b
