### ISSUE TITLE
Should commands be able to change their name dynamically according to context?

### ISSUE THREAD

**Issue by juliendelplanque** [pharo-spec/Commander2#5]

**Comment by jecisc** [comment]
In Change Sorter there was a command that was "Add blabla" if something was nil and "Edit blabla" if it was not nil. So it might have some use.

**Comment by juliendelplanque** [comment]
Yeah I saw a command that was displaying the number of filters in Epicea. That's why I wonder.

**Comment by juliendelplanque** [comment]
It has been implemented.
